apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-budget
  namespace: exam
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-budget
  namespace: exam
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: backend

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mysql-budget
  namespace: exam
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: mysql
