apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: exam
  name: exam-resource-role-binding
subjects:
  - kind: ServiceAccount
    name: default # This applies to all service accounts in the namespace
    namespace: exam
roleRef:
  kind: Role
  name: exam-resource-role
  apiGroup: rbac.authorization.k8s.io
